import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { chromium } from "playwright-core";
import { openEdgePage } from "../src/browser/edge.js";
import { captureWechatArticle } from "../src/mcp/handlers.js";
import { generateArticlePdf } from "../src/article-pdf.js";

test("Edge page-creation errors retain the startup stage even when cleanup fails", async (t) => {
  let closed = 0;
  t.mock.method(chromium, "launchPersistentContext", async () => ({ newPage: async () => { throw new Error("spawn EPERM"); }, close: async () => { closed++; throw new Error("cleanup failed"); } }));
  const result = await captureWechatArticle({ url: "https://mp.weixin.qq.com/s/a" }, { capture: async () => { await openEdgePage(os.tmpdir(), process.execPath); return { status: "complete" }; } });
  assert.match(result.reason ?? "", /启动专用 Edge.*EPERM/);
  assert.equal(closed, 1);
});

test("PDF cleanup failure does not turn generated bytes into a failed result", async (t) => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), "wechat-pdf-close-"));
  await fs.writeFile(path.join(directory, "source.html"), '<div id="js_content">正文</div>');
  let blockedNetwork = false;
  t.mock.method(chromium, "launch", async () => ({ newPage: async (options: { javaScriptEnabled: boolean }) => {
    assert.equal(options.javaScriptEnabled, false);
    return { route: async () => { blockedNetwork = true; }, setContent: async () => {}, pdf: async () => Uint8Array.of(37, 80, 68, 70) };
  }, close: async () => { throw new Error("cleanup failed"); } }));
  const result = await generateArticlePdf(directory, { articleId: "a".repeat(24), title: "测试", sourceUrl: "https://mp.weixin.qq.com/s/a", status: "complete", extractedAt: "2026-09-03", contentHash: "hash" });
  assert.equal(result.status, "saved");
  assert.equal(blockedNetwork, true);
});
